// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMXTM2BkhXzqsPplXhfyKcvdWhhb368-E',
    appId: '1:498785673410:web:845ce5670746387f6f1b5b',
    messagingSenderId: '498785673410',
    projectId: 'local-pavoni',
    authDomain: 'local-pavoni.firebaseapp.com',
    storageBucket: 'local-pavoni.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBM9AMIuOpmpJS1KZfm6Gn7oWciZ0TJcik',
    appId: '1:498785673410:android:aedb7e24312cd1cc6f1b5b',
    messagingSenderId: '498785673410',
    projectId: 'local-pavoni',
    storageBucket: 'local-pavoni.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAgLwsB5VHhb6OqnG_icoWT592zy6N1K8',
    appId: '1:498785673410:ios:c215e820f613c52e6f1b5b',
    messagingSenderId: '498785673410',
    projectId: 'local-pavoni',
    storageBucket: 'local-pavoni.appspot.com',
    iosClientId: '498785673410-qeaga7bbknu6pq58nrpnt983hrteoao4.apps.googleusercontent.com',
    iosBundleId: 'com.local-pavoni.app',
  );
}
